import React, { useState } from 'react';
import { 
  FileText, 
  Download, 
  Trash2, 
  Edit2, 
  Eye, 
  Calendar, 
  Sparkles,
  ShieldCheck,
  Check
} from 'lucide-react';
import { Report } from '../types';
import { formatDate, downloadFile } from '../utils/formatters';
import { ReportModal } from '../components/reports/ReportModal';
import { Modal } from '../components/ui/Modal';

interface ReportsPageProps {
  reports: Report[];
  onRenameReport: (reportId: string, title: string) => Promise<void>;
  onDeleteReport: (reportId: string) => Promise<void>;
}

export const ReportsPage: React.FC<ReportsPageProps> = ({
  reports,
  onRenameReport,
  onDeleteReport
}) => {
  const [selectedReport, setSelectedReport] = useState<Report | null>(null);
  const [renamingReport, setRenamingReport] = useState<Report | null>(null);
  const [newTitle, setNewTitle] = useState('');

  const handleStartRename = (r: Report) => {
    setRenamingReport(r);
    setNewTitle(r.title);
  };

  const handleSaveRename = async () => {
    if (renamingReport && newTitle.trim()) {
      await onRenameReport(renamingReport.id, newTitle.trim());
      setRenamingReport(null);
    }
  };

  const handleDownload = (r: Report) => {
    const filename = `${r.title.toLowerCase().replace(/[^a-z0-9]/g, '_')}.md`;
    downloadFile(r.full_markdown || '', filename, 'text/markdown');
  };

  return (
    <div className="flex-1 overflow-y-auto p-8 max-w-5xl mx-auto space-y-6 animate-in fade-in duration-300">
      {/* Header */}
      <div>
        <h2 className="text-2xl font-bold text-white tracking-tight">Strategic Intelligence Reports</h2>
        <p className="text-xs text-slate-400 mt-1">
          Review, export, and manage executive reports generated by the multi-agent synthesis engine.
        </p>
      </div>

      {/* Reports List */}
      {reports.length === 0 ? (
        <div className="glass-card p-12 rounded-3xl text-center text-slate-500 text-xs space-y-2">
          <FileText className="w-8 h-8 mx-auto text-slate-600" />
          <p>No reports generated yet. Run a strategic analysis task to produce deliverables.</p>
        </div>
      ) : (
        <div className="space-y-3">
          {reports.map((r) => (
            <div
              key={r.id}
              className="glass-card p-5 rounded-2xl flex flex-col sm:flex-row sm:items-center justify-between gap-4 hover:border-slate-700 transition-all"
            >
              <div className="flex items-start gap-3.5 min-w-0">
                <div className="p-3 rounded-xl bg-blue-500/10 text-blue-400 border border-blue-500/20 flex-shrink-0 mt-0.5">
                  <FileText className="w-5 h-5" />
                </div>
                <div className="min-w-0">
                  <h3 className="text-sm font-semibold text-slate-100 truncate">{r.title}</h3>
                  <p className="text-xs text-slate-400 line-clamp-2 mt-1 leading-relaxed">
                    {r.executive_summary || r.summary}
                  </p>
                  <div className="flex items-center gap-3 text-[11px] text-slate-400 font-mono mt-2">
                    <span className="flex items-center gap-1">
                      <Calendar className="w-3 h-3 text-slate-500" />
                      {formatDate(r.created_at)}
                    </span>
                    <span>•</span>
                    <span className="text-emerald-400">{r.key_findings?.length || 0} findings</span>
                    <span>•</span>
                    <span className="text-amber-400">{r.risks?.length || 0} risks</span>
                  </div>
                </div>
              </div>

              <div className="flex items-center gap-2 flex-shrink-0 self-end sm:self-center">
                <button
                  onClick={() => setSelectedReport(r)}
                  className="flex items-center gap-1.5 px-3 py-1.5 bg-blue-600 hover:bg-blue-500 text-white rounded-xl text-xs font-medium shadow-md shadow-blue-600/20 transition-all"
                >
                  <Eye className="w-3.5 h-3.5" />
                  <span>View</span>
                </button>

                <button
                  onClick={() => handleDownload(r)}
                  className="p-2 text-slate-400 hover:text-slate-200 hover:bg-slate-800 rounded-xl transition-colors"
                  title="Download Markdown"
                >
                  <Download className="w-4 h-4" />
                </button>

                <button
                  onClick={() => handleStartRename(r)}
                  className="p-2 text-slate-400 hover:text-slate-200 hover:bg-slate-800 rounded-xl transition-colors"
                  title="Rename report"
                >
                  <Edit2 className="w-4 h-4" />
                </button>

                <button
                  onClick={() => onDeleteReport(r.id)}
                  className="p-2 text-slate-500 hover:text-rose-400 hover:bg-rose-500/10 rounded-xl transition-colors"
                  title="Delete report"
                >
                  <Trash2 className="w-4 h-4" />
                </button>
              </div>
            </div>
          ))}
        </div>
      )}

      {/* Report View Modal */}
      <ReportModal
        report={selectedReport}
        onClose={() => setSelectedReport(null)}
      />

      {/* Rename Modal */}
      <Modal
        isOpen={Boolean(renamingReport)}
        onClose={() => setRenamingReport(null)}
        title="Rename Report"
        maxWidth="md"
      >
        <div className="space-y-4">
          <div className="space-y-1">
            <label className="text-xs font-mono text-slate-400 uppercase">Report Title</label>
            <input
              type="text"
              value={newTitle}
              onChange={(e) => setNewTitle(e.target.value)}
              className="w-full glass-input px-3.5 py-2 rounded-xl text-xs"
            />
          </div>

          <div className="flex justify-end gap-2 pt-2">
            <button
              onClick={() => setRenamingReport(null)}
              className="px-3.5 py-1.5 bg-slate-800 text-slate-300 rounded-lg text-xs hover:bg-slate-700"
            >
              Cancel
            </button>
            <button
              onClick={handleSaveRename}
              className="px-3.5 py-1.5 bg-blue-600 hover:bg-blue-500 text-white rounded-lg text-xs font-medium"
            >
              Save
            </button>
          </div>
        </div>
      </Modal>
    </div>
  );
};
