import React, { useState } from 'react';
import { Modal } from '../ui/Modal';
import { Report } from '../../types';
import { downloadFile, copyToClipboard } from '../../utils/formatters';
import { Download, Copy, Check, FileText, Globe } from 'lucide-react';

interface ReportModalProps {
  report: Report | null;
  onClose: () => void;
}

export const ReportModal: React.FC<ReportModalProps> = ({ report, onClose }) => {
  const [copied, setCopied] = useState(false);

  if (!report) return null;

  const handleCopyMarkdown = async () => {
    const success = await copyToClipboard(report.full_markdown || '');
    if (success) {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  const handleDownloadMarkdown = () => {
    const filename = `${report.title.toLowerCase().replace(/[^a-z0-9]/g, '_')}.md`;
    downloadFile(report.full_markdown || '', filename, 'text/markdown');
  };

  const handleDownloadHTML = () => {
    const htmlContent = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>${report.title}</title>
  <style>
    body { font-family: system-ui, -apple-system, sans-serif; line-height: 1.6; max-width: 900px; margin: 40px auto; padding: 0 20px; color: #1e293b; }
    h1 { color: #0f172a; border-bottom: 2px solid #e2e8f0; padding-bottom: 12px; }
    h2 { color: #1e3a8a; margin-top: 32px; border-bottom: 1px solid #e2e8f0; padding-bottom: 8px; }
    table { width: 100%; border-collapse: collapse; margin: 20px 0; }
    th, td { border: 1px solid #cbd5e1; padding: 10px; text-align: left; }
    th { background: #f8fafc; font-weight: 600; }
    ul, ol { padding-left: 24px; }
    .footer { margin-top: 50px; font-size: 12px; color: #64748b; border-top: 1px solid #e2e8f0; padding-top: 16px; }
  </style>
</head>
<body>
  <h1>${report.title}</h1>
  <p><em>Generated by NEXUS AI Multi-Agent Workspace</em></p>
  
  <h2>1. Executive Summary</h2>
  <p>${report.executive_summary || ''}</p>

  <h2>2. Methodology</h2>
  <p>${(report.methodology || '').replace(/\\n/g, '<br>')}</p>

  <h2>3. Key Findings</h2>
  <ul>${(report.key_findings || []).map(f => `<li>${f}</li>`).join('')}</ul>

  <h2>4. In-Depth Analysis</h2>
  <p>${(report.analysis || '').replace(/\\n/g, '<br>')}</p>

  <h2>5. Strategic Risk Assessment</h2>
  <table>
    <thead>
      <tr><th>Risk</th><th>Category</th><th>Severity</th><th>Mitigation</th></tr>
    </thead>
    <tbody>
      ${(report.risks || []).map(r => `<tr><td>${r.title}</td><td>${r.category || 'Business'}</td><td><strong>${r.severity}</strong></td><td>${r.mitigation}</td></tr>`).join('')}
    </tbody>
  </table>

  <h2>6. Strategic Recommendations</h2>
  <ol>${(report.recommendations || []).map(r => `<li>${r}</li>`).join('')}</ol>

  <h2>7. Conclusion</h2>
  <p>${report.conclusion || ''}</p>

  <div class="footer">NEXUS AI Enterprise Multi-Agent Command Center &copy; 2026</div>
</body>
</html>`;
    const filename = `${report.title.toLowerCase().replace(/[^a-z0-9]/g, '_')}.html`;
    downloadFile(htmlContent, filename, 'text/html');
  };

  return (
    <Modal
      isOpen={Boolean(report)}
      onClose={onClose}
      title={report.title}
      subtitle="Strategic Intelligence Deliverable"
      maxWidth="4xl"
    >
      <div className="space-y-6 text-slate-200">
        {/* Action Header */}
        <div className="flex items-center justify-between pb-4 border-b border-slate-800">
          <div className="flex items-center gap-2 text-xs text-slate-400">
            <FileText className="w-4 h-4 text-blue-400" />
            <span>Structured Multi-Agent Report</span>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={handleCopyMarkdown}
              className="flex items-center gap-1.5 px-3 py-1.5 bg-slate-800 hover:bg-slate-700 text-slate-200 rounded-lg text-xs transition-colors"
            >
              {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
              {copied ? 'Copied MD' : 'Copy Markdown'}
            </button>
            <button
              onClick={handleDownloadMarkdown}
              className="flex items-center gap-1.5 px-3 py-1.5 bg-blue-600/20 hover:bg-blue-600/30 text-blue-300 border border-blue-500/30 rounded-lg text-xs font-medium transition-colors"
            >
              <Download className="w-3.5 h-3.5" />
              Download .MD
            </button>
            <button
              onClick={handleDownloadHTML}
              className="flex items-center gap-1.5 px-3 py-1.5 bg-indigo-600/20 hover:bg-indigo-600/30 text-indigo-300 border border-indigo-500/30 rounded-lg text-xs font-medium transition-colors"
            >
              <Globe className="w-3.5 h-3.5" />
              Download HTML
            </button>
          </div>
        </div>

        {/* Section 1: Executive Summary */}
        <div className="space-y-2">
          <h4 className="text-xs font-mono uppercase tracking-wider text-blue-400 font-semibold">
            1. Executive Summary
          </h4>
          <p className="text-xs text-slate-300 leading-relaxed bg-slate-900/50 p-4 rounded-xl border border-slate-800/80">
            {report.executive_summary}
          </p>
        </div>

        {/* Section 2: Key Findings */}
        <div className="space-y-2">
          <h4 className="text-xs font-mono uppercase tracking-wider text-blue-400 font-semibold">
            2. Key Empirical Findings
          </h4>
          <div className="space-y-1.5">
            {report.key_findings.map((f, i) => (
              <div key={i} className="flex items-start gap-2 text-xs text-slate-300 bg-slate-900/30 p-2.5 rounded-lg border border-slate-800">
                <span className="w-1.5 h-1.5 rounded-full bg-cyan-400 mt-1.5 flex-shrink-0"></span>
                <span>{f}</span>
              </div>
            ))}
          </div>
        </div>

        {/* Section 3: Detailed Analysis */}
        {report.analysis && (
          <div className="space-y-2">
            <h4 className="text-xs font-mono uppercase tracking-wider text-blue-400 font-semibold">
              3. Operational & Market Analysis
            </h4>
            <div className="text-xs text-slate-300 leading-relaxed bg-slate-900/30 p-4 rounded-xl border border-slate-800 whitespace-pre-line">
              {report.analysis}
            </div>
          </div>
        )}

        {/* Section 4: Risk Matrix */}
        {report.risks && report.risks.length > 0 && (
          <div className="space-y-2">
            <h4 className="text-xs font-mono uppercase tracking-wider text-blue-400 font-semibold">
              4. Strategic Risk Surface
            </h4>
            <div className="overflow-x-auto border border-slate-800 rounded-xl">
              <table className="w-full text-xs text-left">
                <thead className="bg-slate-900 text-slate-400 font-mono uppercase text-[11px]">
                  <tr>
                    <th className="p-3">Risk Scenario</th>
                    <th className="p-3">Category</th>
                    <th className="p-3">Severity</th>
                    <th className="p-3">Mitigation Roadmap</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-800">
                  {report.risks.map((r, i) => (
                    <tr key={i} className="hover:bg-slate-900/40">
                      <td className="p-3 font-medium text-slate-200">{r.title}</td>
                      <td className="p-3 text-slate-400">{r.category || 'Business'}</td>
                      <td className="p-3">
                        <span className={`text-[10px] font-mono px-2 py-0.5 rounded-full border ${
                          r.severity === 'Critical' ? 'bg-rose-500/10 text-rose-400 border-rose-500/20' :
                          r.severity === 'High' ? 'bg-amber-500/10 text-amber-400 border-amber-500/20' :
                          'bg-blue-500/10 text-blue-400 border-blue-500/20'
                        }`}>
                          {r.severity}
                        </span>
                      </td>
                      <td className="p-3 text-emerald-400/90 font-mono text-[11px]">{r.mitigation}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        )}

        {/* Section 5: Recommendations */}
        <div className="space-y-2">
          <h4 className="text-xs font-mono uppercase tracking-wider text-blue-400 font-semibold">
            5. Prioritized Actionable Recommendations
          </h4>
          <div className="space-y-2">
            {report.recommendations.map((rec, i) => (
              <div key={i} className="flex items-start gap-3 p-3 bg-slate-900/50 rounded-xl border border-slate-800 text-xs">
                <span className="flex items-center justify-center w-5 h-5 rounded-full bg-blue-600/20 text-blue-400 font-mono font-bold text-[10px] flex-shrink-0">
                  {i + 1}
                </span>
                <span className="text-slate-200 leading-relaxed">{rec}</span>
              </div>
            ))}
          </div>
        </div>

        {/* Section 6: Conclusion */}
        {report.conclusion && (
          <div className="space-y-2">
            <h4 className="text-xs font-mono uppercase tracking-wider text-blue-400 font-semibold">
              6. Strategic Conclusion
            </h4>
            <p className="text-xs text-slate-300 leading-relaxed bg-slate-900/40 p-4 rounded-xl border border-slate-800">
              {report.conclusion}
            </p>
          </div>
        )}
      </div>
    </Modal>
  );
};
