from typing import Dict, Any, Optional, Callable
from app.agents.base import BaseAgent, AgentResult
from app.tools.filesystem.search import search_files
from app.tools.filesystem.create import create_file, read_file
from app.tools.filesystem.move import move_file
from app.tools.filesystem.delete import delete_file
from app.core.security import create_security_ticket

class FileAgent(BaseAgent):
    def __init__(self):
        super().__init__(
            role="file_agent",
            name="Filesystem Operator",
            description="Autonomous file discovery, structured text analysis, safe modification, and organization.",
            capabilities=["Deep File Search", "Directory Indexing", "Metadata Extraction", "Safe File Writes"],
            allowed_tools=["search_files", "create_file", "read_file", "move_file", "delete_file"]
        )

    def execute(
        self,
        prompt: str,
        context: Optional[Dict[str, Any]] = None,
        callback: Optional[Callable[[Dict[str, Any]], None]] = None
    ) -> AgentResult:
        traces = []
        p_lower = prompt.lower()

        traces.append(self.emit_trace(
            action="Analyzing Filesystem Request",
            detail=f"Query: '{prompt}'",
            status="started",
            callback=callback
        ))

        # Check for delete request -> Triggers Security Confirmation!
        if "delete" in p_lower or "remove" in p_lower:
            target = "temp_cache.log"
            for word in prompt.split():
                if "." in word and not word.startswith("http"):
                    target = word.strip(" '\"`")
                    break

            ticket = create_security_ticket(
                operation_name="delete_file",
                description=f"Permit deletion of filesystem resource '{target}'",
                command_or_payload=f"rm {target}",
                agent_role=self.role
            )

            traces.append(self.emit_trace(
                action="Security Gate Triggered: File Deletion",
                detail=f"Operation requires user authorization for target: {target}",
                status="step",
                callback=callback
            ))

            return AgentResult(
                agent_role=self.role,
                response=f"⚠️ **Security Authorization Required**: Nexus File Agent wants permission to delete `{target}`. Please review and confirm below.",
                status="waiting_approval",
                activity_traces=traces,
                security_ticket=ticket
            )

        # Check for create/write request
        elif "create" in p_lower or "write" in p_lower or "make" in p_lower:
            target_name = "nexus_notes.txt"
            sample_content = "# Nexus AI Notes\nGenerated by autonomous File Agent.\nModular desktop intelligence initialized."
            
            tool_call = {"toolName": "create_file", "parameters": {"filepath": target_name, "content": sample_content}}
            res = create_file(target_name, sample_content, overwrite=True)
            tool_call["result"] = res
            tool_call["status"] = "success"

            traces.append(self.emit_trace(
                action=f"Created File: {target_name}",
                detail=f"Written to {res.get('path', target_name)} ({res.get('bytesWritten', 0)} bytes)",
                status="tool_call",
                tool_calls=[tool_call],
                callback=callback
            ))

            return AgentResult(
                agent_role=self.role,
                response=f"Successfully created file **`{target_name}`** with structured content. Path verified and indexed in workspace.",
                status="completed",
                activity_traces=traces,
                data=res
            )

        # Default: Search files
        else:
            pattern = "*.ts*" if "ts" in p_lower else "*.*"
            tool_call = {"toolName": "search_files", "parameters": {"pattern": pattern}}
            res = search_files(directory=".", pattern=pattern, max_results=10)
            tool_call["result"] = res
            tool_call["status"] = "success"

            traces.append(self.emit_trace(
                action=f"Scanned Filesystem ({res.get('count', 0)} matches)",
                detail=f"Pattern: '{pattern}' in workspace",
                status="tool_call",
                tool_calls=[tool_call],
                callback=callback
            ))

            count = res.get("count", 0)
            files_snippet = "\n".join([f"- `{f['name']}` ({f['sizeBytes']} B)" for f in res.get("files", [])[:5]])
            return AgentResult(
                agent_role=self.role,
                response=f"Discovered **{count}** files matching `{pattern}` in current workspace directory.\n\n{files_snippet}",
                status="completed",
                activity_traces=traces,
                data=res
            )
